version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build:prod
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - www/*
  publish:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: .
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file gcloud-service-key.json
      - run: gcloud config set project clay-bar
      - run: gsutil -m rsync -R ./www gs://clay-bar/app/browser

workflows:
  version: 2
  btd:
    jobs:
      - build
      - publish:
          requires:
            - build
