version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6.10.3
       - image: google/cloud-sdk
     steps:
       - run: /opt/google-cloud-sdk/bin/gcloud --version
       - checkout
       - run: npm install
       - run: npm run build:prod
       - run: gcloud compute copy-files ./www clay-bar:/app/
