defaults: &defaults
  working_directory: /tmp
version: 2
jobs:
  build:
#    <<: *defaults
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: npm install
      - run: npm run build:prod
      - persist_to_workspace:
          root: .
          paths:
            - www/*
  publish:
#    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: .
      - run: gcloud compute copy-files ./www clay-bar:/app/

workflows:
  version: 2

  btd:
    jobs:
      - build
      - publish:
          requires:
            - build
