version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6.10.3
     steps:
       - checkout
       - run: npm install
       - run: npm run build:prod
       - run: ./build-scripts/deploy.sh
