version: 2
jobs:
   build:
     docker:
       - image: google/cloud-sdk
       - image: circleci/node:6.10.3
     steps:
       - run: gcloud --version
       - checkout
       - run: npm install
       - run: npm run build:prod
       - run: gcloud compute copy-files ./www clay-bar:/app/
